[book]
authors = ["Casper Cromjongh", "Sander in 't Hout"]
language = "en"
src = "src"
title = "MomentoBooth Documentation"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = []
